### ISSUE TITLE
Decoupling Simulator from Vis

### ISSUE THREAD

**Issue by EvgenyKusmenko** [MontiSim/simulation#15]

**Comment by pbilov** [comment]
Mediator in means of SimulationBuffers for each primary vehicle (vehicle chosen by user).
- Allows users to receive only frames, including their chosen vehicle
- Allows for easy vehicle removal on user logout
- Simulation running time does not depend on user requests, i.e. it stops when it's done, although users' vehicle have not yet reached their destination
